services:
  rplidar:
    image: ghcr.io/screamlab/pros_jetson_driver_image:0.1.0
    env_file:
      - .env
    devices:
      - "/dev/usb_lidar:/dev/usb_lidar"
    volumes:
      - ./demo:/workspace/demo:ro
    networks:
      - cube_bridge_network
    command: "ros2 launch /workspace/demo/rplidar.xml"

networks:
  cube_bridge_network:
    driver: bridge
