services:
  dabai:
    image: ghcr.io/screamlab/pros_jetson_driver_image:0.1.0
    env_file:
      - .env
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    networks:
      - cube_bridge_network
    command: "ros2 launch orbbec_camera dabai_dcw.launch.py"

  rosbridge:
    image: ghcr.io/screamlab/pros_base_image:0.0.2
    env_file:
      - .env
    networks:
      - cube_bridge_network
    ports:
      - 9090:9090
    command: "ros2 launch rosbridge_server rosbridge_websocket_launch.xml"

  compress:
    image: ghcr.io/screamlab/pros_jetson_driver_image:0.1.0
    env_file:
      - .env
    networks:
      - cube_bridge_network
    depends_on:
      - dabai
    command: "ros2 run image_transport republish raw --ros-args --remap in:=camera/color/image_raw -p out:=camera/compressed"

networks:
  cube_bridge_network:
    driver: bridge
