services:
  navigation:
    image: ghcr.io/screamlab/pros_jetson_driver_image:0.1.0
    env_file:
      - .env
    volumes:
      - ./demo:/workspace/demo:ro
    networks:
      - cube_bridge_network
    command: "ros2 launch /workspace/demo/navigation_unity.xml"

# This will create a docker bridge network
# docker network create --driver bridge pros_app_cube_bridge_network
# You can see the network by docker network ls
networks:
  cube_bridge_network:
    driver: bridge
