services:
  image_trans_to_raw:
    image: ghcr.io/screamlab/pros_jetson_driver_image:latest
    env_file:
      - .env
    volumes:
      - ./demo:/workspace/demo:ro
    networks:
      - cube_bridge_network
    command: ros2 run image_transport republish compressed raw --ros-args -r in/compressed:=/camera/image/compressed -r out:=/camera/color/image_raw

networks:
  cube_bridge_network:
    driver: bridge
