services:
  lidar_tranform:
    image: ghcr.io/screamlab/pros_unity_lidar_trans_image:latest
    env_file:
      - .env
    networks:
      - cube_bridge_network
    command: "ros2 run unity_lidar_transformer lidar_transformer_node"

# This will create a docker bridge network
# docker network create --driver bridge pros_app_cube_bridge_network
# You can see the network by docker network ls
networks:
  cube_bridge_network:
    driver: bridge
